export const GET_NEWS="GET_NEWS"
export const GET_POLLS="GET_POLLS"
export const GET_AWARDS="GET_AWARDS"
export const GET_LANGUAGE="GET_LANGUAGE"
export const SIGNIN="SIGNIN"
export const LOGOUT="LOGOUT"
export const UPDATEUSER="UPDATEUSER"