import Social from '../../assets/social issues.png'
import Auto from '../../assets/automobile.png'
import Tech from '../../assets/technology.png'
import Legal from '../../assets/legal.png'
import Crime from '../../assets/crime.png'
import Media from '../../assets/media.png'
import International from '../../assets/international.png'
import Lifestyle from '../../assets/lifestyle.png'
import Entertainment from '../../assets/entertainment.png'
import Sports from '../../assets/sports.png'
import Business from '../../assets/buisness.png'
import IndianPolitics from '../../assets/indian politics.png'
import Elections from '../../assets/elections.png'
import Education from '../../assets/education.png'
import Economy from '../../assets/economy.png'
import Health from '../../assets/health.png'
import Movies from '../../assets/movies.png'
import Fashion from '../../assets/fashion.png'
import SocialIssues from '../../assets/social issues.png'




export const icons = {
  Social,
  Auto,
  Tech,
  Legal,
  Crime,
  Media,
  International,
  Lifestyle,
  Entertainment,
  Sports,
  Business,
  Elections,
  Education,
  Economy,
  Health,
  Movies,
  Fashion,
  "Indian Politics": IndianPolitics,
  "Social": SocialIssues,
  Bollywood: Movies,
  "Social Issues": SocialIssues,
  "Politics": IndianPolitics
}


export const cats = ['Social Issues',
  "Auto",
  "Tech",
  'Legal',
  'Crime',
  'Media',
  'International',
  'Lifestyle',
  'Entertainment',
  'Sports',
  'Business',
  'Indian Politics',
  'Elections',
  'Education',
  'Economy',
  'Health',
  'Movies',
  'Fashion',

]

export const catspa = ['Social Issues',
  "Auto",
  "Tech",
  'Legal',
  'Crime',
  'Media',
  'International',
  'Lifestyle',
  'Entertainment',
  'Sports',
  'Business',
  'Elections',
  'Education',
  'Economy',
  'Health',
  'Fashion',
  'Bollywood',
  "Indian Politics"
]

export const catsAward = ['Social Issues',
  "Tech",
  'Legal',
  'Media',
  'Entertainment',
  'Sports',
  'Business',
  'Elections',
  'Education',
  'Economy',
  'Health',
  'Fashion',
  'Bollywood',
  "Politics"
]

export const hindiTranslate = {
  english: 'अंग्रेज़ी',
  hindi: 'हिंदी',
  notifications: 'नोटिफ़िकेशन',
  invite: 'आमंत्रित करें',
  feedback: 'फीडबैक',
  logout: 'लॉगआउट',
  readmore: 'अधिक पढ़ें',
  share: 'शेयर करें',
  back: 'वापस',
  active: 'ऐक्टिव',
  expired: 'समाप्त',
  viewresult: 'परिणाम देखें',
  youvoted: 'आपका वोट',
  youdidntvote: 'आपने वोट नहीं किया',
  voteanalysis: 'वोट का विश्लेषण',
  overall: 'संपूर्ण',
  totalvotes: 'कुल वोट',
  selectone: 'एक विकल्प चुनें',
  choosecustom: 'कस्टम फ़िल्टर चुनें...',
  nofilter: 'कोई फिल्टर नहीं',
  gender: 'लिंग',
  agegroups: 'आयु समूह',
  region: 'क्षेत्र',
  searchPlaceholderText: 'श्रेणियाँ खोजें',
  noResults: 'कोई परिणाम नहीं',
  pollResult: 'पोल का परिणाम',
  confirm: 'पुष्टि करें',
  selected: 'चुने हुए',
  politics: 'राजनीति',
  bollywood: 'बॉलीवुड',
  sports: 'खेल',
  economy: 'अर्थव्यवस्था',
  fashion: 'फैशन',
  education: 'शिक्षा',
  socialIssues: 'सामाजिक मुद्दे',
  age: 'आयु',
  city: 'शहर',
  state: 'राज्य',
  newsInterest: 'समाचार की रुचि',
  name: 'नाम',
  social: 'सामाजिक',
  auto: 'ऑटोमोबाइल',
  tech: 'प्रौद्योगिकी',
  legal: 'कानून',
  crime: 'अपराध',
  gaming: 'गेमिंग',
  media: 'मीडिया',
  international: 'अंतरराष्ट्रीय',
  lifestyle: 'जीवन शैली',
  entertainment: 'मनोरंजन',
  business: 'व्यापार',
  indianPolitics: 'भारतीय राजनीति',
  indianPolitical: 'भारतीय राजनीति',
  elections: 'चुनाव',
  health: 'स्वास्थ्य',
  movies: 'चलचित्र',
  save: 'विवरण सहेजें',
  home: 'होम',
  polls: 'पोल',
  news: 'समाचार',
  newsHeading: 'न्यूज़',
  videoHeading: 'टिकल - वीडियो स्ट्रीमिंग',
  days: 'दिनों',
  hours: 'घंटे',
  minutes: 'मिनट',
  sharevoice: 'आवाज साझा करें',
  or: 'या',
  copyLink: 'लिंक को कॉपी करें',
  shareIt: 'शेयर',
  postIt: 'पोस्ट',
  tweetIt: 'ट्वीट',
  mailIt: 'मेल',
  enterFeedback: 'प्रतिक्रिया दर्ज करें',
  submit: 'सबमिट',
  completeProfile: 'अपनी प्रोफाइल पूरी कीजिए',
  enterNewsInterest: 'न्यूज़ इंट्रेस्ट दर्ज करें',
  selectGraph: 'ग्राफ का चयन करें',
  by: 'द्वारा',
  privacyPolicy: 'नियम और शर्तें',
  confirmVote: 'वोट की पुष्टि करें',
  yourVote: 'आपका वोट',
  yourVote_first: 'Your',
  yourVote_second: 'Vote',
  discard: 'रद्द करें',
  comments: 'टिप्पणियाँ',
  category: 'श्रेणी',
  novotes: 'कोई वोट नहीं है',
  voteNow: 'वोट करें',
  newsSearchHeader: 'न्यूज़ सर्च',
  videoSearchHeader: 'वीडियो सर्च',
  newsSearchPlaceholderText: 'सर्च',
  pollResultHeader: 'पोल का विस्तृत परिणाम',
  viewMoreReplies: 'और टिप्पणियां देखें',
  hideReplies: 'टिप्पणियों के रिप्लाई को छिपाएं',
  liveTV: 'लाइव टीवी',
  noSearchResults: 'क्षमा करें, आप जो सर्च कर रहे हैं वह हमें नहीं मिला',
  latestNews: 'ताज़ा खबर',
  pollHeader: 'पोल',
  readMoreNews: 'और खबरें पढ़ें',
  qSymbol: 'प्र:',
  shareNow: 'शेयर करें',
  cancel: 'रद्द करें',
  trending: 'ट्रेंडिंग',
  noUpdates: 'कोई अपडेट नहीं है',
  updateRequired: 'अप्डेट अनिवार्य है',
  rateThisApp: 'ऐप को रेट करें',
  suggestAPoll: 'पोल का सुझाव दें',
  enterQuestion: 'प्रश्न लिखें',
  addOption: 'विकल्प लिखें',
  option: 'विकल्प',
  submitting: 'सबमिट कर रहे है',
  editProfile: 'एडिट प्रोफ़ायल',
  edit: 'एडिट',
  pollCommentHeading: 'टिप्पणियाँ',
  loginSignUp: 'लॉग इन/साइन अप',
  questionLengthGreaterThan10: 'प्रश्न कम से कम 10 शब्दों का होना चाहिए',
  chooseOptions: 'विकल्प चुनें',
  guestModalMessage: 'पूर्ण अनुभव का आनंद लेने के लिए, कृपया अपना अकाउंट लॉगिन या रेजिस्टर करें.',
  notNow: 'अभी नहीं',
  okay: 'ओके',
  updatedRequired: 'अप्डेट अनिवार्य है',
  selectMin2NewsInterests: 'न्यूज़ देखने के लिए , आपको न्यूनतम दो न्यूज़ की केटीगटी सलेक्ट करनी होगी',
  darkMode: 'डार्क मोड',
  optionCantBeEmpty: 'विकल्प खाली नहीं हो सकता',
  pollQuestionSubmitted: 'पोल का प्रश्न सफलतापूर्वक सबमिट हो गया है',
  unableToPostQuestion: 'पोल का प्रश्न सबमिट करने में असमर्थ है',
  changeProfilePicture: 'प्रोफ़ायल फ़ोटो बदलें',
  userName: 'यूज़रनेम',
  email: 'ईमेल',
  cityProfile: 'सिटी',
  stateProfile: 'स्टेट',
  pincode: 'पिनकोड',
  dateOfBirth: 'जन्म की तिथि',
  coverPhoto: 'कवर पिक्चर',
  hideProfilePic: 'प्रोफ़ाइल पिक्चर को टिप्पणी में छिपाएँ',
  audio: 'ऑडियो',
  noCommentVote: 'अन्य मतदाताओं की टिप्पणियों को देखने के लिए कृपया इस पोल पर वोट करें',
  darkModeError: 'डार्क मोड को इस्तेमाल करने के लिए लॉगिन/रेजिस्टर करें',
  wallet: 'बटुआ',
  quiz: 'प्रश्नोत्तरी',
  redeem: 'के एवज',
  level: 'स्तर',
  play: 'खेलें',
  unlok1: 'अनलॉक करने के लिए',
  unlok2: 'पिछले स्तरों को पूरा करें',
  questions: 'प्रशन',
  youHave: "आपके पास हैं",
  choseCat: 'क्विज़ की श्रेणी चुनें',
  hint: 'संकेत',
  freeHint: 'मुफ्त संकेत',
  store: 'दुकान',
  award: "अवार्ड",
  awards: 'अवार्डस',
  poll: "मतदान",
  pollTag: "जाने दुनिया क्या सोचती है",
  awardsTag: 'वोट | नॉमिनेट | विजेता तय करें',
  Days: "दिन",
  hrs: "घंटे",
  mins: 'मिनट',
  seconds: 'सेकंड',
  left: "बचे है",
  expiredOn: 'समाप्ति की तिथि',
  awardCat: "अवार्ड श्रेणी",
  nominees: 'प्रत्याशि',
  jury: 'जूरी',
  awardComment: 'टिप्पणियाँ',
  result: 'परिणाम',
  optional: 'टिप्पणी (ओप्शनल)',
  voteSuccess: 'आपका वोट सबमिट हो गया है',
  success: 'सफल',
  alreadyVoted: 'आप पहले वोट कर चुके हैं।',
  declareOn: 'परिणाम घोषित किए जाएंगे',
  audience: 'उपयोगकर्ता',
  total: 'संपूर्ण',
  audVotes: 'उपयोगकर्ताओं के वोट',
  winner: 'विजेता',
  ovRes: 'संपूर्ण परिणाम',
  weght: 'महत्व',
  votes: 'वोट',
  rating: 'रेटिंग',
  median: 'मीडीयन',
  avgRating: 'औसत रेटिंग',
  voteEarn: 'वोट करें और कमाए',
  cong: 'मुबारक हो',
  added: 'आपके वॉलेट में जोड़ दिए गए है',
  noVote: 'इस फिल्टर में शून्य वोट है',
  didntVoteAward: 'आपने इस अवार्ड के लिए वोट नहीं किया',
  giveRating: "रेटिंग दीजिए",
  voteClosed: "वोटिंग समाप्त",
  readMoreOn: "पर और पढ़े",
  noComments: "दिखाने के लिए कोई टिप्पणी नहीं",
  tv: "टीवी",
  videos: "वीडियो",
  yourFeed: "आपकी फ़ीड",
  voted: 'आपका वोट'
}